package com.hym.zhankucompose.model

import kotlinx.serialization.Serializable

/**
{
"articleCount": 81,
"avatar": "https://img.zcool.cn/community/01b4df60532c2f11013e87f40d5ed4.jpg@750w_750h_1c_1e_1o_100sh.jpg",
"bgColor": "",
"bgImageStatus": 1,
"bgImg": "",
"bgImgAlign": 2,
"bgImgLock": 0,
"bgImgRepeat": 0,
"bgImgShow": 0,
"bgImgUrl": "",
"birthday": -315586042000,
"contentRecommendCount": 13135,
"coverImageStatus": 1,
"coverImg": "community/01d34c60532c4311013fb117959970.jpg",
"coverImgUrl": "https://img.zcool.cn/community/01d34c60532c4311013fb117959970.jpg",
"createTime": 1438749950000,
"descript": "我们致力于为艺术设计及相关行业的广大师生，打造一所可以随时开课、自我深造的线上大学。\n\n2015年成立于北京，汇聚全球艺术设计领域的名师精英，以录播课、直播课、线下课等多元化教学方式，提供摄影、设计、绘画、影视、三维等领域的专业课程及服务。目前，我们已拥有超百万学员，不论是零基础的设计爱好者、亟待入行的设计新人，还是自驱进阶的资深设计师，都可以通过300余门包罗万象的在线课程，随时链接行业高手，学习前沿知识，高效快速提升职业竞争力。     ",
"domain": "gogoup",
"email": "",
"faceImageStatus": 1,
"faceName": "01b4df60532c2f11013e87f40d5ed4.jpg",
"facePath": "community",
"fansCount": 33319,
"followingCount": 97,
"gender": 1,
"genderStr": "男",
"graduateYear": 0,
"homeCity": 4170,
"homeCityName": "北京",
"homeProvince": 1,
"homeProvinceName": "亚洲",
"homeViewCount": 341437,
"honors": [...],
"id": 13580089,
"link": "2:=https://weibo.com/p/1006062853342250/home?from=page_100606&mod=TAB#place@*@3:=@*@4:=@*@5:=@*@6:=@*@7:=@*@8:=@*@9:=@*@10:=@*@11:=@*@12:=https://www.gogoup.com@*@",
"major": "",
"manager": 0,
"memberType": 0,
"nowCity": 4170,
"nowCityObj": {...},
"nowDistrictObj": {},
"nowProvince": 247,
"nowProvinceObj": {...},
"openEmail": 1,
"openFavorite": 0,
"pageUrl": "https://gogoup.zcool.com.cn",
"phone": "13*******91",
"pointCount": 303,
"popularityCount": 6281856,
"productCount": 2,
"profession": 23,
"professionObj": {...},
"qq": "863334796",
"qqPrivacy": 1,
"realname": "高高手",
"recommend": 1,
"recommendCount": 13135,
"school": 0,
"schoolName": "",
"signature": "艺术设计在线教育平台",
"source": "",
"statusId": 1,
"tags": "在线教育平台,艺术设计教育",
"username": "站酷学习",
"webAddress": "",
"webShow": 0,
"wechat": "高高手",
"wechatPrivacy": 1,
"workExperienceList": [],
"xueli": 0
}
 */
@Serializable
data class Member(
    val articleCount: Int,
    val avatar: String,
    val bgColor: String,
    val bgImageStatus: Int,
    val bgImg: String,
    val bgImgAlign: Int,
    val bgImgLock: Int,
    val bgImgRepeat: Int,
    val bgImgShow: Int,
    val bgImgUrl: String,
    val birthday: Int,
    val contentRecommendCount: Int,
    val coverImageStatus: Int,
    val coverImg: String,
    val coverImgUrl: String,
    val createTime: Long,
    val descript: String,
    val domain: String,
    val email: String,
    val faceImageStatus: Int,
    val faceName: String,
    val facePath: String,
    val fansCount: Int,
    val followingCount: Int,
    val gender: Int,
    val genderStr: String,
    val graduateYear: Int,
    val homeCity: Int,
    val homeCityName: String,
    val homeProvince: Int,
    val homeProvinceName: String,
    val homeViewCount: Int,
    val honors: List<Honor>,
    val id: Int,
    val link: String,
    val major: String,
    val manager: Int,
    val memberType: Int,
    val nowCity: Int,
    val nowCityObj: NowCityObj,
    val nowDistrictObj: NowDistrictObj,
    val nowProvince: Int,
    val nowProvinceObj: NowProvinceObj,
    val openEmail: Int,
    val openFavorite: Int,
    val pageUrl: String,
    val phone: String,
    val pointCount: Int,
    val popularityCount: Int,
    val productCount: Int,
    val profession: Int,
    val professionObj: ProfessionObj,
    val qq: String,
    val qqPrivacy: Int,
    val realname: String,
    val recommend: Int,
    val recommendCount: Int,
    val school: Int,
    val schoolName: String,
    val signature: String,
    val source: String,
    val statusId: Int,
    val tags: String,
    val username: String,
    val webAddress: String,
    val webShow: Int,
    val wechat: String,
    val wechatPrivacy: Int,
    //val workExperienceList: List<Any>,
    val xueli: Int
)